#!/bin/bash

#MQTT_SERVER=test.mosquitto.org
MQTT_SERVER=home.torbjornsvensson.se
#MQTT_TOPIC=test-12345678
MQTT_TOPIC=presence
MQTT_USER=torbjorn
MQTT_PSWD=tosv4414

#IS_HERE=~/.is_here
IS_HERE=no

#################################

DATE=`date --iso`
TIME=`date +%H:%M`
#echo $NOW

if [ "$IS_HERE" != "no" ]; then
    HERE=`cat $IS_HERE`
#RC=$?
#echo "rc=$RC"
#echo "here=$HERE"
fi

RV=`hcitool scan | grep POCOPHONE`
RC=$?
#RC=0 träff!
#RC=1 ingen träff
#echo "rv=$RC rc='$RV'"
if [ $RC -eq 0 ]; then
    new_here=1
else
    new_here=0
fi

if [ "$IS_HERE" == "no" ]; then
    if [ $new_here -eq 1 ]; then
        msg="{ \"date\": \"$DATE\", \"time\": \"$TIME\", \"tag\": \"BLE\" }"
        cmd="mosquitto_pub -h $MQTT_SERVER -m '$msg' -t $MQTT_TOPIC"
        #echo "$cmd"
        eval "$cmd"
    fi
else
    echo $new_here > $IS_HERE
    if [ $new_here -ne $HERE ]; then
        msg="$DATE;$TIME;$new_here;BLE"
        #echo "REPORT HERE=$new_here"
        cmd="mosquitto_pub -h $MQTT_SERVER -m '$msg' -t $MQTT_TOPIC"
        #echo "$cmd"
        eval "$cmd"
    #else
        #echo "no change"
    fi
fi
