#!/bin/bash

CSV_FILE=/home/torbjorn/ws/precence/data.csv

#################################

DATE=`date --iso`
TIME=`date +%H:%M`
#echo $NOW

RV=`hcitool scan | grep POCOPHONE`
RC=$?
#RC=0 träff!
#RC=1 ingen träff
#echo "rv=$RC rc='$RV'"
if [ $RC -eq 0 ]; then
    new_here=1
else
    new_here=0
fi

if [ $new_here -eq 1 ]; then
    if [ -s $CSV_FILE ]; then
        RC=1
    else
        echo "date,time,tag" >> $CSV_FILE
    fi
    msg="$DATE,$TIME,BLE"
    echo $msg >> $CSV_FILE
fi
